"""add retire_team_id

Revision ID: 08a6d11ca40e
Revises: d7e3f9a2b814
Create Date: 2026-03-30 03:29:18.469179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a6d11ca40e'
down_revision = 'd7e3f9a2b814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retire_team_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('finish_reason', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(None, 'Team', ['retire_team_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Match', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('finish_reason')
        batch_op.drop_column('retire_team_id')

    # ### end Alembic commands ###
