"""add schedule config fields to tournament

Revision ID: 14dae09049ce
Revises: 7ae2f3238fbb
Create Date: 2026-03-02 20:02:35.091203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14dae09049ce'
down_revision = '7ae2f3238fbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_start_time', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('daily_end_time', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('match_duration_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('break_start_time', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('break_end_time', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tournament', schema=None) as batch_op:
        batch_op.drop_column('break_end_time')
        batch_op.drop_column('break_start_time')
        batch_op.drop_column('match_duration_minutes')
        batch_op.drop_column('daily_end_time')
        batch_op.drop_column('daily_start_time')

    # ### end Alembic commands ###
