"""Category Type

Revision ID: 63acf00d6283
Revises: 7ce4f359413c
Create Date: 2026-03-14 19:07:25.554276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63acf00d6283'
down_revision = '7ce4f359413c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Category', schema=None) as batch_op:
        batch_op.drop_column('category_type')

    # ### end Alembic commands ###
