"""add registration_deadline

Revision ID: 7ce4f359413c
Revises: f1ce68ec1f70
Create Date: 2026-03-10 21:40:23.780943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce4f359413c'
down_revision = 'f1ce68ec1f70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_deadline', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tournament', schema=None) as batch_op:
        batch_op.drop_column('registration_deadline')

    # ### end Alembic commands ###
