"""Add status to tournament

Revision ID: 83402560aecd
Revises: ef6bf3fd2fa4
Create Date: 2025-12-08 03:14:10.936749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83402560aecd'
down_revision = 'ef6bf3fd2fa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tournament', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
