"""add stage bracket_position current_stage group_code

Revision ID: b26c31c2173f
Revises: 14dae09049ce
Create Date: 2026-03-03 19:58:53.013432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b26c31c2173f'
down_revision = '14dae09049ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bracket_position', sa.Integer(), nullable=True))

    with op.batch_alter_table('Team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_code', sa.String(length=5), nullable=True))

    with op.batch_alter_table('Tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_stage', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tournament', schema=None) as batch_op:
        batch_op.drop_column('current_stage')

    with op.batch_alter_table('Team', schema=None) as batch_op:
        batch_op.drop_column('group_code')

    with op.batch_alter_table('Match', schema=None) as batch_op:
        batch_op.drop_column('bracket_position')
        batch_op.drop_column('stage')

    # ### end Alembic commands ###
