"""add max_participants to Category

Revision ID: c4b727a2b86f
Revises: 63acf00d6283
Create Date: 2026-03-20 23:02:41.735644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b727a2b86f'
down_revision = '63acf00d6283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_participants', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Category', schema=None) as batch_op:
        batch_op.drop_column('max_participants')

    # ### end Alembic commands ###
