"""add referee application model

Revision ID: d5298d870d6f
Revises: 08a6d11ca40e
Create Date: 2026-04-06 21:07:52.608331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5298d870d6f'
down_revision = '08a6d11ca40e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RefereeApplication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referee_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['referee_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['Tournament.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referee_id', 'tournament_id', name='uq_referee_tournament')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RefereeApplication')
    # ### end Alembic commands ###
