"""Add birth_date gender phone to User

Revision ID: f1ce68ec1f70
Revises: b26c31c2173f
Create Date: 2026-03-08 19:01:43.039730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1ce68ec1f70'
down_revision = 'b26c31c2173f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('gender')
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###
